In [1]:
import numpy as np

(10, 15, 30, 45, 60) değerlerine sahip numpy dizisi oluşturunuz.

In [2]:
np.array([10, 15, 30, 45, 60])

array([10, 15, 30, 45, 60])

(5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

In [3]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

(50 - 100) arasında beşer artarak numpy dizisi oluşturunuz.

In [4]:
np.arange(50, 100, 5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

10 elemanlı sıfırlardan oluşan bir numpy dizisi oluşturunuz.

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

10 elemanlı birlerden oluşan bir numpy dizisi oluşturunuz.

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

(0 - 100) arasında eşit aralıklı 5 sayı üretiniz.

In [7]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

(10 - 30) arasında rastgele 5 sayı üretiniz.

In [8]:
np.random.randint(10, 30, 5)

array([28, 16, 27, 10, 18], dtype=int32)

[0 ve 1] arasında 10 adet sayı üretiniz.

In [9]:
np.random.rand(10)

array([0.19154551, 0.52097154, 0.25949003, 0.41957197, 0.52333725,
       0.42027136, 0.09619609, 0.10067592, 0.56716056, 0.76160677])

(3x5) boyutlarında (10 - 50) arasında rastgele bir matris oluşturunuz.

In [10]:
matris = np.random.randint(10, 50, 15).reshape(3, 5)

matris

array([[36, 26, 35, 32, 16],
       [18, 47, 20, 15, 22],
       [29, 45, 20, 47, 29]], dtype=int32)

Üretilen matrisin satır ve sütun sayıları toplamını bulunuz.

In [11]:
satirToplami = matris.sum(axis= 1)
print(satirToplami)

sutunToplami = matris.sum(axis= 0)
print(sutunToplami)

[145 122 170]
[ 83 118  75  94  67]


Üretilen matrisin en büyük elemanını, en küçük elemanını ve ortalamasını bulunuz.

In [12]:
enBuyuk = matris.max()
print(enBuyuk)

enKucuk = matris.min()
print(enKucuk)

ortalama = matris.mean()
print(ortalama)

47
15
29.133333333333333


Üretilen matrisin en büyük ve en küçük elemanlarının indexlerini bulunuz.

In [13]:
buyukIndex = matris.argmax()
print(buyukIndex)

kucukIndex = matris.argmin()
print(kucukIndex)

6
8


(10 -20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

In [14]:
dizi = np.arange(10, 20)
dizi[:3]

array([10, 11, 12])

Üretilen dizinin elemanlarını tersten yazdırınız.

In [15]:
dizi[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Üretilen matrisin ilk satırını seçiniz.

In [16]:
matris[0]

array([36, 26, 35, 32, 16], dtype=int32)

Üretilen matrisin 2. satır 3. sütunundaki elemanını bulunuz.

In [17]:
matris[1, 2]

# matris[1][2]

np.int32(20)

Üretilen matrisin tüm satırlardaki ilk elemanını seçiniz.

In [18]:
matris[:,0]

array([36, 18, 29], dtype=int32)

Üretilen matrisin tüm sütunlardaki ilk elemanını seçiniz.

In [19]:
matris[0,:]

array([36, 26, 35, 32, 16], dtype=int32)

Üretilen matrisin tüm elemanlarının karesini alınız.

In [20]:
matris ** 2

array([[1296,  676, 1225, 1024,  256],
       [ 324, 2209,  400,  225,  484],
       [ 841, 2025,  400, 2209,  841]], dtype=int32)