ARRAY OLUŞTURMA

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [3]:
np.zeros(3, dtype= int)

array([0, 0, 0])

In [4]:
np.ones(3, dtype= int)

array([1, 1, 1])

In [5]:
np.full(3, 10)

array([10, 10, 10])

In [6]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [7]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
np.linspace(0, 50, 5, dtype= int)

array([ 0, 12, 25, 37, 50])

In [9]:
np.random.randint(0, 10, (2, 2))

array([[3, 2],
       [6, 9]], dtype=int32)

ARRAY ÖZELLİKLERİ

* ndim -> Boyut sayısı 
* shape -> Boyut bilgisi
* size -> Eleman sayısı
* dtype -> Eleman veri tipi

In [10]:
a = np.random.randint(5, size= 3)

a

array([0, 1, 4], dtype=int32)

In [11]:
a.ndim

1

In [12]:
a.shape

(3,)

In [13]:
b  = np.random.randint(10, size= (2, 2))

b

array([[6, 5],
       [1, 4]], dtype=int32)

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 2)

In [16]:
b.size

4

ARRAY YENİDEN ŞEKİLLENDİRME (RESHAPE)

In [17]:
a = np.arange(0, 12, 2)

a

array([ 0,  2,  4,  6,  8, 10])

In [18]:
print(a.ndim)

print(a.shape)

1
(6,)


In [19]:
b = a.reshape(3, 2)

b

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [20]:
print(b.ndim)

print(b.shape)

2
(3, 2)


ARRAY BİRLEŞTİRME (CONCAT)

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [22]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([a, a], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

ARRAY AYIRMA (SPLİT)

In [26]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x, y, z = np.split(a, [3, 6])

In [28]:
print(x)

print(y)

print(z)

[1 2 3]
[4 5 6]
[7 8 9]


ARRAY SIRALAMA (SORT)

In [29]:
a = np.array([8,3,7,2])

a

array([8, 3, 7, 2])

In [30]:
np.sort(a)

array([2, 3, 7, 8])

In [31]:
b = np.array([[5, 1, 3], [6, 4, 2]])

b

array([[5, 1, 3],
       [6, 4, 2]])

In [32]:
np.sort(b)

array([[1, 3, 5],
       [2, 4, 6]])

ARRAY ELEMANLARINA ERİŞME

In [33]:
a = np.random.randint(10, size= 5)

a

array([6, 1, 2, 9, 6], dtype=int32)

In [34]:
print(a[0])

print(a[-1])

6
6


In [35]:
a[1] = 3

a

array([6, 3, 2, 9, 6], dtype=int32)

In [36]:
b = np.random.randint(10, size=(2, 3))

b

array([[0, 2, 0],
       [9, 3, 7]], dtype=int32)

In [37]:
print(b[1, 2])

7


In [38]:
b[0, 0] = 2

b

array([[2, 2, 0],
       [9, 3, 7]], dtype=int32)

ARRAY ALT KÜME İŞLEMLERİ (SLİCE)

In [39]:
a = np.arange(20, 26)

a

array([20, 21, 22, 23, 24, 25])

In [40]:
a[0:3]

array([20, 21, 22])

In [41]:
a[3:]

array([23, 24, 25])

In [42]:
a[0::2]

array([20, 22, 24])

In [43]:
b = np.random.randint(10, size= (3, 3))

b

array([[8, 5, 9],
       [1, 2, 6],
       [5, 5, 2]], dtype=int32)

In [44]:
b[:, 2]

array([9, 6, 2], dtype=int32)

In [45]:
b[0, :]

array([8, 5, 9], dtype=int32)

In [46]:
b[0:2, 1:]

array([[5, 9],
       [2, 6]], dtype=int32)

MATEMATİKSEL İŞLEMLER

In [47]:
a = np.array([10, 20, 30, 40, 50])

a

array([10, 20, 30, 40, 50])

In [48]:
np.add(a, 10)

array([20, 30, 40, 50, 60])

In [49]:
np.subtract(a, 10)

array([ 0, 10, 20, 30, 40])

In [50]:
np.multiply(a, 10)

array([100, 200, 300, 400, 500])

In [51]:
np.divide(a, 10)

array([1., 2., 3., 4., 5.])

In [52]:
np.power(a, 2)

array([ 100,  400,  900, 1600, 2500])

In [53]:
np.mod(a, 9)

array([1, 2, 3, 4, 5])

İSTATİSTİKSEL İŞLEMLER

In [54]:
a = np.array([10, 20, 30, 40, 50])

a

array([10, 20, 30, 40, 50])

In [55]:
np.mean(a)

np.float64(30.0)

In [56]:
np.sum(a)

np.int64(150)

In [57]:
np.min(a)

np.int64(10)

In [58]:
np.max(a)

np.int64(50)

In [59]:
np.var(a)

np.float64(200.0)

In [60]:
np.std(a)

np.float64(14.142135623730951)