PANDAS SERİLERİ

In [1]:
import numpy as np

import pandas as pd

In [2]:
s = pd.Series([1, 2, 3, 4, 5])

s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
print(s[0])

print(s[4])

1
5


In [4]:
s.size

5

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s.ndim

1

In [7]:
s.values

array([1, 2, 3, 4, 5])

In [8]:
s2 = pd.Series([10, 20, 30, 40, 50], index=["A", "B", "C", "D", "E"])

s2

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [9]:
print(s2["A"])

print(s2["E"])

10
50


In [10]:
s2.size

5

In [11]:
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [12]:
s2.ndim

1

In [13]:
s2.values

array([10, 20, 30, 40, 50])

In [14]:
pd.concat([s, s2])

0     1
1     2
2     3
3     4
4     5
A    10
B    20
C    30
D    40
E    50
dtype: int64

PANDAS DATAFRAMELERİ

In [15]:
df = pd.DataFrame([1, 2, 3, 4, 5])

df

0
0  1
1  2
2  3
3  4
4  5

In [16]:
df[0][2]

np.int64(3)

In [17]:
df.size

5

In [18]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
df.ndim

2

In [20]:
df.values

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
df2 = pd.DataFrame([[1, 2], [3, 4], [5, 6]], columns= ["Sütun 1", "Sütun 2"], index= ["Satır 1", "Satır 2", "Satır 3"])

df2

Sütun 1  Sütun 2
Satır 1        1        2
Satır 2        3        4
Satır 3        5        6

In [22]:
df2["Sütun 1"]

Satır 1    1
Satır 2    3
Satır 3    5
Name: Sütun 1, dtype: int64

In [23]:
df2["Sütun 2"]["Satır 3"]

np.int64(6)

In [24]:
df2.size

6

In [25]:
df2.index

Index(['Satır 1', 'Satır 2', 'Satır 3'], dtype='object')

In [26]:
df2.ndim

2

In [27]:
df2.values

array([[1, 2],
       [3, 4],
       [5, 6]])

PANDAS İNDEXLEME (LOC - ILOC)

In [28]:
a = np.random.randint(1, 10, (5, 2))

df = pd.DataFrame(a, columns= ["sutun1", "sutun2"])

df

sutun1  sutun2
0       8       4
1       3       8
2       7       4
3       7       1
4       1       8

In [29]:
df.iloc[0:2]

sutun1  sutun2
0       8       4
1       3       8

In [30]:
df.loc[0:2]

sutun1  sutun2
0       8       4
1       3       8
2       7       4

In [31]:
df.iloc[0:3]["sutun1"]

0    8
1    3
2    7
Name: sutun1, dtype: int32

In [32]:
df.loc[0:3]["sutun2"]

0    4
1    8
2    4
3    1
Name: sutun2, dtype: int32

PANDAS KOŞULLU ELEMAN SEÇİMLERİ

In [33]:
df[df.sutun1 > 2]

sutun1  sutun2
0       8       4
1       3       8
2       7       4
3       7       1

In [34]:
df[(df.sutun1 > 3) & (df.sutun2 < 3)]

sutun1  sutun2
3       7       1

PANDAS DATAFRAME BİRLEŞTİRME

In [35]:
df

sutun1  sutun2
0       8       4
1       3       8
2       7       4
3       7       1
4       1       8

In [36]:
df2 = df * 10

df2

sutun1  sutun2
0      80      40
1      30      80
2      70      40
3      70      10
4      10      80

In [37]:
pd.concat([df, df2], ignore_index= True)

sutun1  sutun2
0       8       4
1       3       8
2       7       4
3       7       1
4       1       8
5      80      40
6      30      80
7      70      40
8      70      10
9      10      80

PANDAS İLE İSTATİSTİK

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [38]:
a = np.random.randint(1, 20, size= (5, 3))
df = pd.DataFrame(a)

df.index = ["Sa1", "Sa2", "Sa3", "Sa4", "Sa5"]
df.columns = ["Sü1", "Sü2", "Sü3"]

df

Sü1  Sü2  Sü3
Sa1   14   14    9
Sa2    6    1   14
Sa3    9    6   14
Sa4    4    2    9
Sa5    6    3   17

In [39]:
df.describe()

Sü1        Sü2        Sü3
count   5.000000   5.000000   5.000000
mean    7.800000   5.200000  12.600000
std     3.898718   5.263079   3.507136
min     4.000000   1.000000   9.000000
25%     6.000000   2.000000   9.000000
50%     6.000000   3.000000  14.000000
75%     9.000000   6.000000  14.000000
max    14.000000  14.000000  17.000000

PANDAS İLE GRUPLAMA

In [40]:
df = pd.DataFrame(
    {
        "gruplar" : ["A", "B", "C", "A", "B", "C"],
        "veriler" : [10, 20, 30, 40, 50, 60]
    }
)

df

gruplar  veriler
0       A       10
1       B       20
2       C       30
3       A       40
4       B       50
5       C       60

In [41]:
df.groupby("gruplar").sum()

veriler
gruplar         
A             50
B             70
C             90

In [42]:
df.groupby("gruplar").count()

veriler
gruplar         
A              2
B              2
C              2

In [43]:
df.groupby("gruplar").mean()

veriler
gruplar         
A           25.0
B           35.0
C           45.0